### 数据基本信息查看

#### 导入 pandas 包

In [1]:
import pandas as pd

#### 加载 data 目录下的 LJdata.csv 数据，并显示数据的前 5 行数据

,区域,地址,标题,户型,面积,价格,楼层,建造时间,朝向,更新时间,看房人数,备注,链接地址
0,燕莎租房,新源街,亮马桥 新源街 精装两居 交通便利 看房方便 随时入住,2室1厅,50,5800,中楼层(共6层),1981年建板楼,南,2017.07.21,26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101803342.html
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
2,广安门租房,远见名苑,远见名苑 东向两居室 独立小区环境 适合居家,2室1厅,86,8000,低楼层(共25层),2006年建塔楼,东,2017.07.20,34,距离7号线达官营站684米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101756753.html
3,天通苑租房,天通苑北一区,北一区简装两居，采光好，视野美，出行方便,2室1厅,103,5300,低楼层(共13层),2004年建板楼,东南,2017.07.25,30,距离5号线天通苑站927米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101780034.html
4,团结湖租房,团结湖北口,团结湖北口近地铁高楼层朝南向精装修正规两居室,2室1厅,63,6400,高楼层(共16层),1982年建塔楼,南,2017.07.26,30,距离10号线团结湖站88米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101781083.html

#### 查看数据的形状(行列数量)

(2760, 13)

#### 查看数据集基本信息：每个字段值的数量、是否非空值，以及该字段的数据类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2760 entries, 0 to 2759
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   区域      2760 non-null   object
 1   地址      2760 non-null   object
 2   标题      2760 non-null   object
 3   户型      2760 non-null   object
 4   面积      2760 non-null   int64
 5   价格      2760 non-null   int64
 6   楼层      2760 non-null   object
 7   建造时间    2758 non-null   object
 8   朝向      2760 non-null   object
 9   更新时间    2760 non-null   object
 10  看房人数    2760 non-null   int64
 11  备注      2760 non-null   object
 12  链接地址    2760 non-null   object
dtypes: int64(3), object(10)
memory usage: 280.4+ KB

#### 获取加载数据的行标签和列标签

RangeIndex(start=0, stop=2760, step=1)

Index(['区域', '地址', '标题', '户型', '面积', '价格', '楼层', '建造时间', '朝向', '更新时间', '看房人数',
       '备注', '链接地址'],
      dtype='object')

#### 修改加载数据的列标签

In [8]:
# 列标签修改为：['district', 'address', 'title', 'house_type', 'area', 'price', 'floor', 
#                'build_time', 'direction', 'update_time', 'view_num', 'extra_info', 'link']

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
0,燕莎租房,新源街,亮马桥 新源街 精装两居 交通便利 看房方便 随时入住,2室1厅,50,5800,中楼层(共6层),1981年建板楼,南,2017.07.21,26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101803342.html
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
2,广安门租房,远见名苑,远见名苑 东向两居室 独立小区环境 适合居家,2室1厅,86,8000,低楼层(共25层),2006年建塔楼,东,2017.07.20,34,距离7号线达官营站684米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101756753.html
3,天通苑租房,天通苑北一区,北一区简装两居，采光好，视野美，出行方便,2室1厅,103,5300,低楼层(共13层),2004年建板楼,东南,2017.07.25,30,距离5号线天通苑站927米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101780034.html
4,团结湖租房,团结湖北口,团结湖北口近地铁高楼层朝南向精装修正规两居室,2室1厅,63,6400,高楼层(共16层),1982年建塔楼,南,2017.07.26,30,距离10号线团结湖站88米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101781083.html

#### 查看数据集中，所有数值型字段的基本统计信息

              area          price     view_num
count  2760.000000    2760.000000  2760.000000
mean     87.658696    7570.800725    13.448913
std      41.862928    6316.204986    12.746202
min      19.000000    1300.000000     0.000000
25%      58.000000    4500.000000     4.000000
50%      80.000000    6000.000000    10.000000
75%     103.000000    8500.000000    19.000000
max     720.000000  210000.000000   122.000000

#### 查看数据集中，所有非数值型字段的基本统计信息

,district,address,title,house_type,floor,build_time,direction,update_time,extra_info,link
count,2760,2760,2760,2760,2760,2758,2760,2760,2760,2760
unique,208,1473,2369,24,105,138,35,14,1343,2381
top,望京租房,远洋山水,禾乔丽致公寓 诚意出租 看房随时 有钥匙,2室1厅,高楼层(共6层),2004年建塔楼,南 北,2017.07.26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101660289.html
freq,109,19,4,1284,323,78,1009,634,469,3

### 数据的获取操作

#### 获取行标签为1，3，5行的district、address、title列的数据

  district address                     title
1     望京租房    澳洲康都    澳洲康都东向精致两居室...........
3    天通苑租房  天通苑北一区      北一区简装两居，采光好，视野美，出行方便
5    回龙观租房     龙华园  龙泽龙华园57平低楼层一居室家具家电齐全拎包入住

#### 获取行标签为1，3，5行的所有列的数据

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
3,天通苑租房,天通苑北一区,北一区简装两居，采光好，视野美，出行方便,2室1厅,103,5300,低楼层(共13层),2004年建板楼,东南,2017.07.25,30,距离5号线天通苑站927米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101780034.html
5,回龙观租房,龙华园,龙泽龙华园57平低楼层一居室家具家电齐全拎包入住,1室1厅,58,4000,低楼层(共6层),1994年建板楼,南,2017.07.23,61,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101748994.html

#### 获取所有行的district、address、title列的数据

     district address                         title
0        燕莎租房     新源街  亮马桥 新源街  精装两居 交通便利 看房方便 随时入住
1        望京租房    澳洲康都        澳洲康都东向精致两居室...........
2       广安门租房    远见名苑        远见名苑 东向两居室 独立小区环境 适合居家
3       天通苑租房  天通苑北一区          北一区简装两居，采光好，视野美，出行方便
4       团结湖租房   团结湖北口        团结湖北口近地铁高楼层朝南向精装修正规两居室
...       ...     ...                           ...
2755     朝青租房   天鹅湾北区              天鹅湾北区 1室1厅 9500元
2756    太阳宫租房     水星园      水星园精装一居室  可自带家具家电 业主也可配齐
2757    六里桥租房    莲花小区          莲花小区 西南两居室 温馨舒适 楼层合适
2758    陶然亭租房  中海紫御公馆            中海紫御公馆  把您的家安放在花园里
2759    三元桥租房     曙光里              曙光里南向 高层两居室 随时看房

[2760 rows x 3 columns]

#### 获取行位置为 0，1，2行的列位置为0，1，2列的数据

  district address                         title
0     燕莎租房     新源街  亮马桥 新源街  精装两居 交通便利 看房方便 随时入住
1     望京租房    澳洲康都        澳洲康都东向精致两居室...........
2    广安门租房    远见名苑        远见名苑 东向两居室 独立小区环境 适合居家

#### 获取行位置为 0，1，2行的所有列的数据

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
0,燕莎租房,新源街,亮马桥 新源街 精装两居 交通便利 看房方便 随时入住,2室1厅,50,5800,中楼层(共6层),1981年建板楼,南,2017.07.21,26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101803342.html
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
2,广安门租房,远见名苑,远见名苑 东向两居室 独立小区环境 适合居家,2室1厅,86,8000,低楼层(共25层),2006年建塔楼,东,2017.07.20,34,距离7号线达官营站684米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101756753.html

#### 获取所有行的列位置为0，1，2列的数据

     district address                         title
0        燕莎租房     新源街  亮马桥 新源街  精装两居 交通便利 看房方便 随时入住
1        望京租房    澳洲康都        澳洲康都东向精致两居室...........
2       广安门租房    远见名苑        远见名苑 东向两居室 独立小区环境 适合居家
3       天通苑租房  天通苑北一区          北一区简装两居，采光好，视野美，出行方便
4       团结湖租房   团结湖北口        团结湖北口近地铁高楼层朝南向精装修正规两居室
...       ...     ...                           ...
2755     朝青租房   天鹅湾北区              天鹅湾北区 1室1厅 9500元
2756    太阳宫租房     水星园      水星园精装一居室  可自带家具家电 业主也可配齐
2757    六里桥租房    莲花小区          莲花小区 西南两居室 温馨舒适 楼层合适
2758    陶然亭租房  中海紫御公馆            中海紫御公馆  把您的家安放在花园里
2759    三元桥租房     曙光里              曙光里南向 高层两居室 随时看房

[2760 rows x 3 columns]

#### 使用[]的形式获取district、address、title列的数据

     district address                         title
0        燕莎租房     新源街  亮马桥 新源街  精装两居 交通便利 看房方便 随时入住
1        望京租房    澳洲康都        澳洲康都东向精致两居室...........
2       广安门租房    远见名苑        远见名苑 东向两居室 独立小区环境 适合居家
3       天通苑租房  天通苑北一区          北一区简装两居，采光好，视野美，出行方便
4       团结湖租房   团结湖北口        团结湖北口近地铁高楼层朝南向精装修正规两居室
...       ...     ...                           ...
2755     朝青租房   天鹅湾北区              天鹅湾北区 1室1厅 9500元
2756    太阳宫租房     水星园      水星园精装一居室  可自带家具家电 业主也可配齐
2757    六里桥租房    莲花小区          莲花小区 西南两居室 温馨舒适 楼层合适
2758    陶然亭租房  中海紫御公馆            中海紫御公馆  把您的家安放在花园里
2759    三元桥租房     曙光里              曙光里南向 高层两居室 随时看房

[2760 rows x 3 columns]

#### 使用[]的形式获取district列的数据

0        燕莎租房
1        望京租房
2       广安门租房
3       天通苑租房
4       团结湖租房
        ...
2755     朝青租房
2756    太阳宫租房
2757    六里桥租房
2758    陶然亭租房
2759    三元桥租房
Name: district, Length: 2760, dtype: object

### 数据的统计操作

#### 示例1：查看房屋租金的最高价格、最低价格、平均值和中位数

210000

1300

7570.800724637681

6000.0

#### 示例2：找到租金最低和最高的房子的全部信息

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
2527,良乡租房,伟业嘉园西里,半地下室 家电齐全 集中供暖 简单装修,1室1厅,46,1300,地下室(共5层),2005年建,南,2017.07.19,14,随时看房 集中供暖,https://bj.lianjia.com/zufang/101101538484.html

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
2658,和平里租房,雍和家园二期,雍和家园 底商出租 使用面积720米,6室3厅,720,210000,低楼层(共6层),2005年建板楼,南,2017.07.26,21,距离2号线雍和宫站293米 随时看房 集中供暖,https://bj.lianjia.com/zufang/101101672514.html

#### 示例3：查看望京租房价格在5000以下的房屋信息

,district,address,title,house_type,area,price,floor,build_time,direction,update_time,view_num,extra_info,link
1186,望京租房,点击未来,西门子 望京大厦 点击未来 精装公寓 诚意出租,1室0厅,44,4900,低楼层(共14层),2004年建板塔结合,西北,2017.07.26,12,距离14号线(东段)阜通站671米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101777951.html
2196,望京租房,南湖东园二区,南湖东园二区 1室1厅 4500元,1室1厅,55,4500,低楼层(共14层),1998年建塔楼,东,2017.07.25,9,距离15号线望京站378米 随时看房 集中供暖,https://bj.lianjia.com/zufang/101101787302.html

#### 示例4：查看望京租房的最低租房价格、最高租房价格、平均租房价格

4500

30000

11055.963302752294